/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppVerificationRouteImport } from './routes/app.verification'
import { Route as AppSecretariatRouteImport } from './routes/app.secretariat'
import { Route as AppRepresentationRouteImport } from './routes/app.representation'
import { Route as AppRechercheRouteImport } from './routes/app.recherche'
import { Route as AppProfilRouteImport } from './routes/app.profil'
import { Route as AppParkingRouteImport } from './routes/app.parking'
import { Route as AppManifestRouteImport } from './routes/app.manifest'
import { Route as AppLocalisationRouteImport } from './routes/app.localisation'
import { Route as AppEntrepotsRouteImport } from './routes/app.entrepots'
import { Route as AppDossiersRouteImport } from './routes/app.dossiers'
import { Route as AppConfigurationRouteImport } from './routes/app.configuration'
import { Route as AppComptesRouteImport } from './routes/app.comptes'
import { Route as AppColisageRouteImport } from './routes/app.colisage'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AppBarrieresRouteImport } from './routes/app.barrieres'
import { Route as AppAppurementRouteImport } from './routes/app.appurement'
import { Route as AppAlertesRouteImport } from './routes/app.alertes'
import { Route as AppManifestManifestIdRouteImport } from './routes/app.manifest.$manifestId'
import { Route as AppEntrepotsEntrepotIdRouteImport } from './routes/app.entrepots.$entrepotId'
import { Route as AppDossiersDossierIdRouteImport } from './routes/app.dossiers.$dossierId'
import { Route as AppDirectionsDirectionIdRouteImport } from './routes/app.directions.$directionId'
import { Route as AppComptesCompteIdRouteImport } from './routes/app.comptes.$compteId'
import { Route as AppBureauxBureauIdRouteImport } from './routes/app.bureaux.$bureauId'
import { Route as AppBarrieresBarriereIdRouteImport } from './routes/app.barrieres.$barriereId'
import { Route as AppAlertesAlerteIdRouteImport } from './routes/app.alertes.$alerteId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVerificationRoute = AppVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AppRoute,
} as any)
const AppSecretariatRoute = AppSecretariatRouteImport.update({
  id: '/secretariat',
  path: '/secretariat',
  getParentRoute: () => AppRoute,
} as any)
const AppRepresentationRoute = AppRepresentationRouteImport.update({
  id: '/representation',
  path: '/representation',
  getParentRoute: () => AppRoute,
} as any)
const AppRechercheRoute = AppRechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilRoute = AppProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AppRoute,
} as any)
const AppParkingRoute = AppParkingRouteImport.update({
  id: '/parking',
  path: '/parking',
  getParentRoute: () => AppRoute,
} as any)
const AppManifestRoute = AppManifestRouteImport.update({
  id: '/manifest',
  path: '/manifest',
  getParentRoute: () => AppRoute,
} as any)
const AppLocalisationRoute = AppLocalisationRouteImport.update({
  id: '/localisation',
  path: '/localisation',
  getParentRoute: () => AppRoute,
} as any)
const AppEntrepotsRoute = AppEntrepotsRouteImport.update({
  id: '/entrepots',
  path: '/entrepots',
  getParentRoute: () => AppRoute,
} as any)
const AppDossiersRoute = AppDossiersRouteImport.update({
  id: '/dossiers',
  path: '/dossiers',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigurationRoute = AppConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => AppRoute,
} as any)
const AppComptesRoute = AppComptesRouteImport.update({
  id: '/comptes',
  path: '/comptes',
  getParentRoute: () => AppRoute,
} as any)
const AppColisageRoute = AppColisageRouteImport.update({
  id: '/colisage',
  path: '/colisage',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppBarrieresRoute = AppBarrieresRouteImport.update({
  id: '/barrieres',
  path: '/barrieres',
  getParentRoute: () => AppRoute,
} as any)
const AppAppurementRoute = AppAppurementRouteImport.update({
  id: '/appurement',
  path: '/appurement',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertesRoute = AppAlertesRouteImport.update({
  id: '/alertes',
  path: '/alertes',
  getParentRoute: () => AppRoute,
} as any)
const AppManifestManifestIdRoute = AppManifestManifestIdRouteImport.update({
  id: '/$manifestId',
  path: '/$manifestId',
  getParentRoute: () => AppManifestRoute,
} as any)
const AppEntrepotsEntrepotIdRoute = AppEntrepotsEntrepotIdRouteImport.update({
  id: '/$entrepotId',
  path: '/$entrepotId',
  getParentRoute: () => AppEntrepotsRoute,
} as any)
const AppDossiersDossierIdRoute = AppDossiersDossierIdRouteImport.update({
  id: '/$dossierId',
  path: '/$dossierId',
  getParentRoute: () => AppDossiersRoute,
} as any)
const AppDirectionsDirectionIdRoute =
  AppDirectionsDirectionIdRouteImport.update({
    id: '/directions/$directionId',
    path: '/directions/$directionId',
    getParentRoute: () => AppRoute,
  } as any)
const AppComptesCompteIdRoute = AppComptesCompteIdRouteImport.update({
  id: '/$compteId',
  path: '/$compteId',
  getParentRoute: () => AppComptesRoute,
} as any)
const AppBureauxBureauIdRoute = AppBureauxBureauIdRouteImport.update({
  id: '/bureaux/$bureauId',
  path: '/bureaux/$bureauId',
  getParentRoute: () => AppRoute,
} as any)
const AppBarrieresBarriereIdRoute = AppBarrieresBarriereIdRouteImport.update({
  id: '/$barriereId',
  path: '/$barriereId',
  getParentRoute: () => AppBarrieresRoute,
} as any)
const AppAlertesAlerteIdRoute = AppAlertesAlerteIdRouteImport.update({
  id: '/$alerteId',
  path: '/$alerteId',
  getParentRoute: () => AppAlertesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/alertes': typeof AppAlertesRouteWithChildren
  '/app/appurement': typeof AppAppurementRoute
  '/app/barrieres': typeof AppBarrieresRouteWithChildren
  '/app/chat': typeof AppChatRoute
  '/app/colisage': typeof AppColisageRoute
  '/app/comptes': typeof AppComptesRouteWithChildren
  '/app/configuration': typeof AppConfigurationRoute
  '/app/dossiers': typeof AppDossiersRouteWithChildren
  '/app/entrepots': typeof AppEntrepotsRouteWithChildren
  '/app/localisation': typeof AppLocalisationRoute
  '/app/manifest': typeof AppManifestRouteWithChildren
  '/app/parking': typeof AppParkingRoute
  '/app/profil': typeof AppProfilRoute
  '/app/recherche': typeof AppRechercheRoute
  '/app/representation': typeof AppRepresentationRoute
  '/app/secretariat': typeof AppSecretariatRoute
  '/app/verification': typeof AppVerificationRoute
  '/app/': typeof AppIndexRoute
  '/app/alertes/$alerteId': typeof AppAlertesAlerteIdRoute
  '/app/barrieres/$barriereId': typeof AppBarrieresBarriereIdRoute
  '/app/bureaux/$bureauId': typeof AppBureauxBureauIdRoute
  '/app/comptes/$compteId': typeof AppComptesCompteIdRoute
  '/app/directions/$directionId': typeof AppDirectionsDirectionIdRoute
  '/app/dossiers/$dossierId': typeof AppDossiersDossierIdRoute
  '/app/entrepots/$entrepotId': typeof AppEntrepotsEntrepotIdRoute
  '/app/manifest/$manifestId': typeof AppManifestManifestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/alertes': typeof AppAlertesRouteWithChildren
  '/app/appurement': typeof AppAppurementRoute
  '/app/barrieres': typeof AppBarrieresRouteWithChildren
  '/app/chat': typeof AppChatRoute
  '/app/colisage': typeof AppColisageRoute
  '/app/comptes': typeof AppComptesRouteWithChildren
  '/app/configuration': typeof AppConfigurationRoute
  '/app/dossiers': typeof AppDossiersRouteWithChildren
  '/app/entrepots': typeof AppEntrepotsRouteWithChildren
  '/app/localisation': typeof AppLocalisationRoute
  '/app/manifest': typeof AppManifestRouteWithChildren
  '/app/parking': typeof AppParkingRoute
  '/app/profil': typeof AppProfilRoute
  '/app/recherche': typeof AppRechercheRoute
  '/app/representation': typeof AppRepresentationRoute
  '/app/secretariat': typeof AppSecretariatRoute
  '/app/verification': typeof AppVerificationRoute
  '/app': typeof AppIndexRoute
  '/app/alertes/$alerteId': typeof AppAlertesAlerteIdRoute
  '/app/barrieres/$barriereId': typeof AppBarrieresBarriereIdRoute
  '/app/bureaux/$bureauId': typeof AppBureauxBureauIdRoute
  '/app/comptes/$compteId': typeof AppComptesCompteIdRoute
  '/app/directions/$directionId': typeof AppDirectionsDirectionIdRoute
  '/app/dossiers/$dossierId': typeof AppDossiersDossierIdRoute
  '/app/entrepots/$entrepotId': typeof AppEntrepotsEntrepotIdRoute
  '/app/manifest/$manifestId': typeof AppManifestManifestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/alertes': typeof AppAlertesRouteWithChildren
  '/app/appurement': typeof AppAppurementRoute
  '/app/barrieres': typeof AppBarrieresRouteWithChildren
  '/app/chat': typeof AppChatRoute
  '/app/colisage': typeof AppColisageRoute
  '/app/comptes': typeof AppComptesRouteWithChildren
  '/app/configuration': typeof AppConfigurationRoute
  '/app/dossiers': typeof AppDossiersRouteWithChildren
  '/app/entrepots': typeof AppEntrepotsRouteWithChildren
  '/app/localisation': typeof AppLocalisationRoute
  '/app/manifest': typeof AppManifestRouteWithChildren
  '/app/parking': typeof AppParkingRoute
  '/app/profil': typeof AppProfilRoute
  '/app/recherche': typeof AppRechercheRoute
  '/app/representation': typeof AppRepresentationRoute
  '/app/secretariat': typeof AppSecretariatRoute
  '/app/verification': typeof AppVerificationRoute
  '/app/': typeof AppIndexRoute
  '/app/alertes/$alerteId': typeof AppAlertesAlerteIdRoute
  '/app/barrieres/$barriereId': typeof AppBarrieresBarriereIdRoute
  '/app/bureaux/$bureauId': typeof AppBureauxBureauIdRoute
  '/app/comptes/$compteId': typeof AppComptesCompteIdRoute
  '/app/directions/$directionId': typeof AppDirectionsDirectionIdRoute
  '/app/dossiers/$dossierId': typeof AppDossiersDossierIdRoute
  '/app/entrepots/$entrepotId': typeof AppEntrepotsEntrepotIdRoute
  '/app/manifest/$manifestId': typeof AppManifestManifestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/alertes'
    | '/app/appurement'
    | '/app/barrieres'
    | '/app/chat'
    | '/app/colisage'
    | '/app/comptes'
    | '/app/configuration'
    | '/app/dossiers'
    | '/app/entrepots'
    | '/app/localisation'
    | '/app/manifest'
    | '/app/parking'
    | '/app/profil'
    | '/app/recherche'
    | '/app/representation'
    | '/app/secretariat'
    | '/app/verification'
    | '/app/'
    | '/app/alertes/$alerteId'
    | '/app/barrieres/$barriereId'
    | '/app/bureaux/$bureauId'
    | '/app/comptes/$compteId'
    | '/app/directions/$directionId'
    | '/app/dossiers/$dossierId'
    | '/app/entrepots/$entrepotId'
    | '/app/manifest/$manifestId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/alertes'
    | '/app/appurement'
    | '/app/barrieres'
    | '/app/chat'
    | '/app/colisage'
    | '/app/comptes'
    | '/app/configuration'
    | '/app/dossiers'
    | '/app/entrepots'
    | '/app/localisation'
    | '/app/manifest'
    | '/app/parking'
    | '/app/profil'
    | '/app/recherche'
    | '/app/representation'
    | '/app/secretariat'
    | '/app/verification'
    | '/app'
    | '/app/alertes/$alerteId'
    | '/app/barrieres/$barriereId'
    | '/app/bureaux/$bureauId'
    | '/app/comptes/$compteId'
    | '/app/directions/$directionId'
    | '/app/dossiers/$dossierId'
    | '/app/entrepots/$entrepotId'
    | '/app/manifest/$manifestId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/alertes'
    | '/app/appurement'
    | '/app/barrieres'
    | '/app/chat'
    | '/app/colisage'
    | '/app/comptes'
    | '/app/configuration'
    | '/app/dossiers'
    | '/app/entrepots'
    | '/app/localisation'
    | '/app/manifest'
    | '/app/parking'
    | '/app/profil'
    | '/app/recherche'
    | '/app/representation'
    | '/app/secretariat'
    | '/app/verification'
    | '/app/'
    | '/app/alertes/$alerteId'
    | '/app/barrieres/$barriereId'
    | '/app/bureaux/$bureauId'
    | '/app/comptes/$compteId'
    | '/app/directions/$directionId'
    | '/app/dossiers/$dossierId'
    | '/app/entrepots/$entrepotId'
    | '/app/manifest/$manifestId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/verification': {
      id: '/app/verification'
      path: '/verification'
      fullPath: '/app/verification'
      preLoaderRoute: typeof AppVerificationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/secretariat': {
      id: '/app/secretariat'
      path: '/secretariat'
      fullPath: '/app/secretariat'
      preLoaderRoute: typeof AppSecretariatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/representation': {
      id: '/app/representation'
      path: '/representation'
      fullPath: '/app/representation'
      preLoaderRoute: typeof AppRepresentationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recherche': {
      id: '/app/recherche'
      path: '/recherche'
      fullPath: '/app/recherche'
      preLoaderRoute: typeof AppRechercheRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profil': {
      id: '/app/profil'
      path: '/profil'
      fullPath: '/app/profil'
      preLoaderRoute: typeof AppProfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/parking': {
      id: '/app/parking'
      path: '/parking'
      fullPath: '/app/parking'
      preLoaderRoute: typeof AppParkingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/manifest': {
      id: '/app/manifest'
      path: '/manifest'
      fullPath: '/app/manifest'
      preLoaderRoute: typeof AppManifestRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/localisation': {
      id: '/app/localisation'
      path: '/localisation'
      fullPath: '/app/localisation'
      preLoaderRoute: typeof AppLocalisationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/entrepots': {
      id: '/app/entrepots'
      path: '/entrepots'
      fullPath: '/app/entrepots'
      preLoaderRoute: typeof AppEntrepotsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dossiers': {
      id: '/app/dossiers'
      path: '/dossiers'
      fullPath: '/app/dossiers'
      preLoaderRoute: typeof AppDossiersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuration': {
      id: '/app/configuration'
      path: '/configuration'
      fullPath: '/app/configuration'
      preLoaderRoute: typeof AppConfigurationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/comptes': {
      id: '/app/comptes'
      path: '/comptes'
      fullPath: '/app/comptes'
      preLoaderRoute: typeof AppComptesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/colisage': {
      id: '/app/colisage'
      path: '/colisage'
      fullPath: '/app/colisage'
      preLoaderRoute: typeof AppColisageRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/barrieres': {
      id: '/app/barrieres'
      path: '/barrieres'
      fullPath: '/app/barrieres'
      preLoaderRoute: typeof AppBarrieresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/appurement': {
      id: '/app/appurement'
      path: '/appurement'
      fullPath: '/app/appurement'
      preLoaderRoute: typeof AppAppurementRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alertes': {
      id: '/app/alertes'
      path: '/alertes'
      fullPath: '/app/alertes'
      preLoaderRoute: typeof AppAlertesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/manifest/$manifestId': {
      id: '/app/manifest/$manifestId'
      path: '/$manifestId'
      fullPath: '/app/manifest/$manifestId'
      preLoaderRoute: typeof AppManifestManifestIdRouteImport
      parentRoute: typeof AppManifestRoute
    }
    '/app/entrepots/$entrepotId': {
      id: '/app/entrepots/$entrepotId'
      path: '/$entrepotId'
      fullPath: '/app/entrepots/$entrepotId'
      preLoaderRoute: typeof AppEntrepotsEntrepotIdRouteImport
      parentRoute: typeof AppEntrepotsRoute
    }
    '/app/dossiers/$dossierId': {
      id: '/app/dossiers/$dossierId'
      path: '/$dossierId'
      fullPath: '/app/dossiers/$dossierId'
      preLoaderRoute: typeof AppDossiersDossierIdRouteImport
      parentRoute: typeof AppDossiersRoute
    }
    '/app/directions/$directionId': {
      id: '/app/directions/$directionId'
      path: '/directions/$directionId'
      fullPath: '/app/directions/$directionId'
      preLoaderRoute: typeof AppDirectionsDirectionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/comptes/$compteId': {
      id: '/app/comptes/$compteId'
      path: '/$compteId'
      fullPath: '/app/comptes/$compteId'
      preLoaderRoute: typeof AppComptesCompteIdRouteImport
      parentRoute: typeof AppComptesRoute
    }
    '/app/bureaux/$bureauId': {
      id: '/app/bureaux/$bureauId'
      path: '/bureaux/$bureauId'
      fullPath: '/app/bureaux/$bureauId'
      preLoaderRoute: typeof AppBureauxBureauIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/barrieres/$barriereId': {
      id: '/app/barrieres/$barriereId'
      path: '/$barriereId'
      fullPath: '/app/barrieres/$barriereId'
      preLoaderRoute: typeof AppBarrieresBarriereIdRouteImport
      parentRoute: typeof AppBarrieresRoute
    }
    '/app/alertes/$alerteId': {
      id: '/app/alertes/$alerteId'
      path: '/$alerteId'
      fullPath: '/app/alertes/$alerteId'
      preLoaderRoute: typeof AppAlertesAlerteIdRouteImport
      parentRoute: typeof AppAlertesRoute
    }
  }
}

interface AppAlertesRouteChildren {
  AppAlertesAlerteIdRoute: typeof AppAlertesAlerteIdRoute
}

const AppAlertesRouteChildren: AppAlertesRouteChildren = {
  AppAlertesAlerteIdRoute: AppAlertesAlerteIdRoute,
}

const AppAlertesRouteWithChildren = AppAlertesRoute._addFileChildren(
  AppAlertesRouteChildren,
)

interface AppBarrieresRouteChildren {
  AppBarrieresBarriereIdRoute: typeof AppBarrieresBarriereIdRoute
}

const AppBarrieresRouteChildren: AppBarrieresRouteChildren = {
  AppBarrieresBarriereIdRoute: AppBarrieresBarriereIdRoute,
}

const AppBarrieresRouteWithChildren = AppBarrieresRoute._addFileChildren(
  AppBarrieresRouteChildren,
)

interface AppComptesRouteChildren {
  AppComptesCompteIdRoute: typeof AppComptesCompteIdRoute
}

const AppComptesRouteChildren: AppComptesRouteChildren = {
  AppComptesCompteIdRoute: AppComptesCompteIdRoute,
}

const AppComptesRouteWithChildren = AppComptesRoute._addFileChildren(
  AppComptesRouteChildren,
)

interface AppDossiersRouteChildren {
  AppDossiersDossierIdRoute: typeof AppDossiersDossierIdRoute
}

const AppDossiersRouteChildren: AppDossiersRouteChildren = {
  AppDossiersDossierIdRoute: AppDossiersDossierIdRoute,
}

const AppDossiersRouteWithChildren = AppDossiersRoute._addFileChildren(
  AppDossiersRouteChildren,
)

interface AppEntrepotsRouteChildren {
  AppEntrepotsEntrepotIdRoute: typeof AppEntrepotsEntrepotIdRoute
}

const AppEntrepotsRouteChildren: AppEntrepotsRouteChildren = {
  AppEntrepotsEntrepotIdRoute: AppEntrepotsEntrepotIdRoute,
}

const AppEntrepotsRouteWithChildren = AppEntrepotsRoute._addFileChildren(
  AppEntrepotsRouteChildren,
)

interface AppManifestRouteChildren {
  AppManifestManifestIdRoute: typeof AppManifestManifestIdRoute
}

const AppManifestRouteChildren: AppManifestRouteChildren = {
  AppManifestManifestIdRoute: AppManifestManifestIdRoute,
}

const AppManifestRouteWithChildren = AppManifestRoute._addFileChildren(
  AppManifestRouteChildren,
)

interface AppRouteChildren {
  AppAlertesRoute: typeof AppAlertesRouteWithChildren
  AppAppurementRoute: typeof AppAppurementRoute
  AppBarrieresRoute: typeof AppBarrieresRouteWithChildren
  AppChatRoute: typeof AppChatRoute
  AppColisageRoute: typeof AppColisageRoute
  AppComptesRoute: typeof AppComptesRouteWithChildren
  AppConfigurationRoute: typeof AppConfigurationRoute
  AppDossiersRoute: typeof AppDossiersRouteWithChildren
  AppEntrepotsRoute: typeof AppEntrepotsRouteWithChildren
  AppLocalisationRoute: typeof AppLocalisationRoute
  AppManifestRoute: typeof AppManifestRouteWithChildren
  AppParkingRoute: typeof AppParkingRoute
  AppProfilRoute: typeof AppProfilRoute
  AppRechercheRoute: typeof AppRechercheRoute
  AppRepresentationRoute: typeof AppRepresentationRoute
  AppSecretariatRoute: typeof AppSecretariatRoute
  AppVerificationRoute: typeof AppVerificationRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBureauxBureauIdRoute: typeof AppBureauxBureauIdRoute
  AppDirectionsDirectionIdRoute: typeof AppDirectionsDirectionIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertesRoute: AppAlertesRouteWithChildren,
  AppAppurementRoute: AppAppurementRoute,
  AppBarrieresRoute: AppBarrieresRouteWithChildren,
  AppChatRoute: AppChatRoute,
  AppColisageRoute: AppColisageRoute,
  AppComptesRoute: AppComptesRouteWithChildren,
  AppConfigurationRoute: AppConfigurationRoute,
  AppDossiersRoute: AppDossiersRouteWithChildren,
  AppEntrepotsRoute: AppEntrepotsRouteWithChildren,
  AppLocalisationRoute: AppLocalisationRoute,
  AppManifestRoute: AppManifestRouteWithChildren,
  AppParkingRoute: AppParkingRoute,
  AppProfilRoute: AppProfilRoute,
  AppRechercheRoute: AppRechercheRoute,
  AppRepresentationRoute: AppRepresentationRoute,
  AppSecretariatRoute: AppSecretariatRoute,
  AppVerificationRoute: AppVerificationRoute,
  AppIndexRoute: AppIndexRoute,
  AppBureauxBureauIdRoute: AppBureauxBureauIdRoute,
  AppDirectionsDirectionIdRoute: AppDirectionsDirectionIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
